#' Merged Node Support Table
#'
#' A table containing merged node support values from both Bayesian and Maximum Likelihood (ML)
#' phylogenetic trees. This table was created by merging the node support information from node
#' tables for the ML (`data_ML_node_table`) and the Bayesian (`data_bayesian_node_table`) trees,
#' which were first generated by `phylo_node_table()`.
#'
#' @format A data frame with the following columns:
#' \itemize{
#'   \item \code{Taxa} Character. The taxa associated with each node.
#'   \item \code{Node_ML} Integer. The bootstrap value for each node in the ML tree.
#'   \item \code{Node_Bayesian} Integer. The posterior probability for each node (converted to whole numbers) in the Bayesian tree.
#'   \item \code{Support_Values} Numeric. The node support values, displayed as "bootstrap values"/"posterior probability values" assigned to common nodes.
#' }
#'
#' @details
#' The `data_merged_table` contains the combined node support values from ML and Bayesian phylogenetic trees.
#' This table facilitates comparative analyses of node support between methods and is useful for
#' downstream analyses and visualization of phylogenetic support values.
#'
#' @examples
#' data(data_merged_table)
#' head(data_merged_table)
#'
#' # Example: Merging Bayesian and ML node support tables to generate data_merged_table
#' data(data_bayesian_node_table)
#' data(data_ml_node_table)
#' data_merged_table <- phylo_merge_nodes(
#'   data_bayesian_node_table,
#'   data_ml_node_table)
#'
#' @seealso
#' \code{\link{phylo_node_table}}, \code{\link{phylo_merge_nodes}}, \code{\link{data_treeBayesian}}, \code{\link{data_treeML}}
#'
#' @source
#' The support values for the ML tree were obtained from bootstrap values generated in IQ-TREE.
#' The support values for the Bayesian tree were calculated based on posterior probabilities in MrBayes and converted to whole numbers in TreeGraph2.
"data_merged_table"
